# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaul7y < Formula
  desc "A simple terminal application/TUI for interacting with HashiCorp Vault."
  homepage "https://github.com/dkyanakiev/vaul7y"
  version "0.1.4"

  on_macos do
    url "https://github.com/dkyanakiev/vaul7y/releases/download/v0.1.4/vaul7y_0.1.4_Darwin_all.tar.gz"
    sha256 "a6bc885ca137ecfca4bb67f6456f653ef832f1ff605d79931e225a30357ef50b"

    def install
      bin.install "vaul7y"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dkyanakiev/vaul7y/releases/download/v0.1.4/vaul7y_0.1.4_Linux_arm64.tar.gz"
      sha256 "e45b0009eab25212f7236d4eae1889b121cb5cc85e97fa8c6853f850e6b722e7"

      def install
        bin.install "vaul7y"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dkyanakiev/vaul7y/releases/download/v0.1.4/vaul7y_0.1.4_Linux_x86_64.tar.gz"
      sha256 "d84c8e6caad4d488ae5d80bb67f9cda36767fb55c17ca4767197994c0e957320"

      def install
        bin.install "vaul7y"
      end
    end
  end
end
