# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vault7y < Formula
  desc "A simple terminal application/TUI for interacting with HashiCorp Vault."
  homepage "https://github.com/dkyanakiev/vault7y"
  version "0.0.3"

  on_macos do
    url "https://github.com/dkyanakiev/vaul7y/releases/download/v0.0.3/vaul7y_0.0.3_Darwin_all.tar.gz"
    sha256 "e3234fbc11e55dfb56c47bf9f5bcc6c6df7b02dd368a0e05e84d068563ca98cc"

    def install
      bin.install "vaul7y"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dkyanakiev/vaul7y/releases/download/v0.0.3/vaul7y_0.0.3_Linux_arm64.tar.gz"
      sha256 "89aa6958a001a0b05bb085bc2ea66c4fa1828989def8ccb30ded68c9df3edfc4"

      def install
        bin.install "vaul7y"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dkyanakiev/vaul7y/releases/download/v0.0.3/vaul7y_0.0.3_Linux_x86_64.tar.gz"
      sha256 "fa65acf00cb9719d0a70d03d0b415cc305e42edb0b001adea7e6bc9c91caef8e"

      def install
        bin.install "vaul7y"
      end
    end
  end
end
