# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaul7y < Formula
  desc "A simple terminal application/TUI for interacting with HashiCorp Vault."
  homepage "https://github.com/dkyanakiev/vaul7y"
  version "0.1.3"

  on_macos do
    url "https://github.com/dkyanakiev/vaul7y/releases/download/v0.1.3/vaul7y_0.1.3_Darwin_all.tar.gz"
    sha256 "dcd2ce7e071abb5ed0492b9871289cdff4c09e58435cb4fb6242d99119ae0c20"

    def install
      bin.install "vaul7y"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dkyanakiev/vaul7y/releases/download/v0.1.3/vaul7y_0.1.3_Linux_arm64.tar.gz"
      sha256 "d41aa022f8cd538291b2d11343e5489c9ff5720cb749bc860880ca33fd7d2ad2"

      def install
        bin.install "vaul7y"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dkyanakiev/vaul7y/releases/download/v0.1.3/vaul7y_0.1.3_Linux_x86_64.tar.gz"
      sha256 "84392184cd2f9be0f113f33d41b373c2e3b140c533df6bf09164e7af5eef3866"

      def install
        bin.install "vaul7y"
      end
    end
  end
end
